{% set name = "conduit" %}
{% set version = "0.9.4" %}
{% set sha256 = "c9edfb2ff09890084313ad9c2d83bfb7c10e70b696980762d1ae1488f9f08e6c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/LLNL/conduit/releases/download/v{{ version }}/conduit-v{{ version }}-src-with-blt.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}  # [unix]
    - make                       # [linux]
    - cmake
  host:
    - {{ mpi }}  # [mpi != 'nompi']
    - libpython-static  # [py>=38]
    - python
    - pip
    - numpy
    - openssl
    - hdf5
    - zlib
  run:
    - {{ mpi }}  # [mpi != 'nompi']
    - python
    - zlib

test:
  requires:
    - numpy
  commands:
    - test -f $PREFIX/lib/libconduit.dylib  # [osx]
    - test -f $PREFIX/lib/libconduit.so     # [linux]
    - if not exist %PREFIX%\\Library\\lib\\conduit.lib exit 1  # [win]
  imports:
    - conduit
    - conduit.relay
    - conduit.blueprint
about:
  home: https://github.com/LLNL/conduit
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simplified Data Exchange for HPC Simulations

  description: |
    Conduit is an open source project from Lawrence Livermore National
    Laboratory that provides an intuitive model for describing hierarchical
    scientific data in C++, C, Fortran, and Python. It is used for data\
    coupling between packages in-core, serialization, and I/O tasks.
  doc_url: https://software.llnl.gov/conduit
  dev_url: https://github.com/LLNL/conduit

extra:
  recipe-maintainers:
    - cyrush
