{% set version = "0.8.4" %}

package:
  name: conduit
  version: {{ version }}

source:
  url: https://github.com/LLNL/conduit/releases/download/v{{ version }}/conduit-v{{ version }}-src-with-blt.tar.gz
  sha256: 55c37ddc668dbc45d43b60c440192f76e688a530d64f9fe1a9c7fdad8cd525fd

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}  # [unix]
    - make                       # [linux]
    - cmake
  host:
    - openssl           # [linux]
    - {{ mpi }}         # [mpi != 'nompi']
    - libpython-static  # [py>=38]
    - python
    - numpy
    - hdf5
    - zlib
  run:
    - {{ mpi }}  # [mpi != 'nompi']
    - python

test:
  requires:
    - numpy
  commands:
    - test -f $PREFIX/lib/libconduit.dylib  # [osx]
    - test -f $PREFIX/lib/libconduit.so     # [linux]
    - if not exist %PREFIX%\\Library\\lib\\conduit.lib exit 1  # [win]
  imports:
    - conduit
    - conduit.relay
    - conduit.blueprint
about:
  home: https://github.com/LLNL/conduit
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simplified Data Exchange for HPC Simulations

  description: |
    Conduit is an open source project from Lawrence Livermore National
    Laboratory that provides an intuitive model for describing hierarchical
    scientific data in C++, C, Fortran, and Python. It is used for data\
    coupling between packages in-core, serialization, and I/O tasks.
  doc_url: https://software.llnl.gov/conduit
  dev_url: https://github.com/LLNL/conduit

extra:
  recipe-maintainers:
    - cyrush
